#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YinXiangMa.Captcha
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 3 "..\..\YinXiangMaCaptcha.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 4 "..\..\YinXiangMaCaptcha.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 5 "..\..\YinXiangMaCaptcha.cshtml"
    using YinXiangMa_lib;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class YinXiangMaCaptcha : System.Web.WebPages.HelperPage
    {
        
        #line 8 "..\..\YinXiangMaCaptcha.cshtml"

    private const string YXM_Url = "http://api.yinxiangma.com/api3/yzm.yinxiangma.php";
    // TODO: no https for YXM
    private const string YXM_SecureUrl = YXM_Url;
    private const string YXM_Version = "YinXiangMaJsSDK_4.0";//"YinXiangMaDotNetSDK_4.0";

    internal static bool HandleValidateResponse(HttpContextBase context, string response)
    {
        if (!String.IsNullOrEmpty(response))
        {
            return response == "true";
        }
        return false;
    }

    private static string GetUrlHelper(HttpContextBase context, string publicKey)
    {
        if (String.IsNullOrEmpty(publicKey))
        {
            throw new ArgumentException("arg can't be null", "publicKey");
        }

        var builder = new StringBuilder(context.Request.IsSecureConnection ? YXM_SecureUrl : YXM_Url);
        builder.AppendFormat("?pk={0}", publicKey);
        builder.AppendFormat("&v={0}", YXM_Version);
        return builder.ToString();
    }

    internal static string GetChallengeUrl(HttpContextBase httpContext, string publicKey = null)
    {
        return GetUrlHelper(httpContext, publicKey);
    }

    private static string ExecuteValidateRequest(HttpContextBase context, string privateKey)
    {
        return YinXiangMa.Check_Answer(privateKey, context.Request.Form["YinXiangMa_challenge"], context.Request.Form["YXM_level"], context.Request.Form["YXM_input_result"]);
    }

    internal static bool Validate(HttpContextBase context, string privateKey)
    {
        if (String.IsNullOrEmpty(privateKey))
        {
            throw new ArgumentException("arg can't be null", "privateKey");
        }

        string result = ExecuteValidateRequest(context, privateKey);

        return HandleValidateResponse(context, result);
    }

    public static bool Validate(string privateKey = null)
    {
        return Validate(HttpContext.Current == null ? null : new HttpContextWrapper(HttpContext.Current), privateKey);
    }


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult GetHtml(HttpContextBase httpContext, string publicKey = null, object options = null)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 66 "..\..\YinXiangMaCaptcha.cshtml"
 
    if (options != null)
    {
        var optionJson = new HtmlString(JsonConvert.SerializeObject(options));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <script>\r\n            var captcha_YXM_Options = ");



#line 71 "..\..\YinXiangMaCaptcha.cshtml"
       WriteTo(@__razor_helper_writer, optionJson);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ";\r\n        </script>\r\n");



#line 73 "..\..\YinXiangMaCaptcha.cshtml"
    }
    else
    {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <script>\r\n            var captcha_YXM_Options = {};\r\n        </script>\r\n");



#line 79 "..\..\YinXiangMaCaptcha.cshtml"
    }


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @"    <script>
        // override YXM default behavior only if enableFromSubmitCheck not true
        if (!captcha_YXM_Options.enableFromSubmitCheck) {

            // set dummies to fool YXM, this will prevent creating of YinXiangMa object
            var YinXiangMa = {};

            YinXiangMa.init = function () { };
        }
    </script>
");



#line 91 "..\..\YinXiangMaCaptcha.cshtml"


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <input type=\'hidden\' id=\'YXM_here\' />\r\n");



#line 93 "..\..\YinXiangMaCaptcha.cshtml"


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <script type=\'text/javascript\' charset=\'gbk\' id=\'YXM_script\' src=\"");



#line 94 "..\..\YinXiangMaCaptcha.cshtml"
                                       WriteTo(@__razor_helper_writer, GetChallengeUrl(httpContext, publicKey));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"></script>\r\n");



#line 95 "..\..\YinXiangMaCaptcha.cshtml"


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @"    <script type='text/javascript' charset='gbk'>

        // TODO: integrate with jquery validation
        // override YXM default behavior only if enableFromSubmitCheck not true
        if (!captcha_YXM_Options.enableFromSubmitCheck) {

            // keep tying until condition satisfied % callback called
            function fireWhenReady(conditionFunc, callback) {
                if (jQuery.isFunction(conditionFunc) && conditionFunc() && callback) {
                    callback();
                }
                else {
                    setTimeout(function() {
                        fireWhenReady(conditionFunc, callback);
                    }, 100);
                }
            }

            // init YinXiangMa without form submit event
            function YinXiangMaInitPatch() {

                // init YXM object instead of them
                YinXiangMa = new YinXiangMaObject(YinXiangMaDataJson);

                YinXiangMa.initcss();

                // init YXM, set captcha html
                (function(YinXiangMa, data) {
                    var c = YinXiangMa.html[data.type];
                    if (c != undefined) {
                        YXM_here.outerHTML = c;
                        YinXiangMa._bn();
                    } else {
                        YinXiangMa.exception();
                    }
                })(YinXiangMa, YXM_YinXiangMaData || YinXiangMaDataJson);
            }

            ");



WriteLiteralTo(@__razor_helper_writer, "\r\n\r\n            $(function() {\r\n                fireWhenReady(function() {\r\n     " +
"                   return typeof YinXiangMaObject !== \'undefined\';\r\n            " +
"        }, YinXiangMaInitPatch);\r\n            });\r\n\r\n        }\r\n\r\n");



#line 147 "..\..\YinXiangMaCaptcha.cshtml"
         if (HttpContext.Current.IsDebuggingEnabled)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            ");

WriteLiteralTo(@__razor_helper_writer, "  function YXM_valided_true() {\r\n            console.log(\"good captcha\");\r\n      " +
"  }\r\n        function YXM_valided_false() {\r\n            console.log(\"bad captch" +
"a\");\r\n        }");

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 155 "..\..\YinXiangMaCaptcha.cshtml"
        }
        else
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            ");

WriteLiteralTo(@__razor_helper_writer, "  function YXM_valided_true() {\r\n        }\r\n        function YXM_valided_false() " +
"{\r\n        }");

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 162 "..\..\YinXiangMaCaptcha.cshtml"
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n    </script>\r\n");



#line 165 "..\..\YinXiangMaCaptcha.cshtml"


#line default
#line hidden

});

}


        public YinXiangMaCaptcha()
        {
        }
    }
}
#pragma warning restore 1591
